apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server 
## mengacu ke component deploymentserver    
  ports:
    - port: 5000
#port artinya port yg akan diakses oleh other objects
      targetPort: 5000
## target port artinya container pod
